# Carbon Suboxide

Force constants taken from https://sci-hub.se/https://pubs.rsc.org/en/content/articlelanding/1937/jr/jr9370001396/unauth#!divAbstract


- oxygen mass = 16 amu
- carbon mass = 12 amu
- K = 14.87  N/cm
- k = 14.15  N/cm




In [6]:
import numpy as np
import matplotlib.pyplot as plt
from scipy.linalg import eig

In [7]:
%%time
# Mass in AMU
m1 = m5 = 16       # Oxygen 
m2 = m3 = m4 = 12  # Carbon

# Mass matrix
M = np.zeros( (5,5) )
M[0,0] = m1
M[1,1] = m2
M[2,2] = m3
M[3,3] = m4
M[4,4] = m5


# Spring constants in N/cm
k12 = 14.87
k23 = 14.15
k34 = 14.15
k45 = 14.87

K = np.array([
    [  +k12,   -k12,        0.0,         0.0,         0.0  ],
    [  -k12,   +k12 + k23,  -k23,        0.0,         0.0  ],
    [  0.0,    -k23,        +k23 + k34,  -k34,        0.0  ],
    [  0.0,    0.0,         -k34,        +k34 + k45,  -k45 ],
    [  0.0,    0.0,         0.0,         -k45,        +k45 ]])
print ('Mass matrix:')
print(M)
print ('Spring matrix:')
print(K)

Mass matrix:
[[16.  0.  0.  0.  0.]
 [ 0. 12.  0.  0.  0.]
 [ 0.  0. 12.  0.  0.]
 [ 0.  0.  0. 12.  0.]
 [ 0.  0.  0.  0. 16.]]
Spring matrix:
[[ 14.87 -14.87   0.     0.     0.  ]
 [-14.87  29.02 -14.15   0.     0.  ]
 [  0.   -14.15  28.3  -14.15   0.  ]
 [  0.     0.   -14.15  29.02 -14.87]
 [  0.     0.     0.   -14.87  14.87]]
CPU times: user 10.4 ms, sys: 0 ns, total: 10.4 ms
Wall time: 10.3 ms


In [8]:
%%time
# Eigenvector calculations
omega,v = eig(K,M)

for i,o in enumerate(omega):
    print("---------------------")
    print("Eigenvalue = %6.2f" % (o))    
    print("Eigenvector ", v[:,i] )

---------------------
Eigenvalue =   4.24
Eigenvector  [ 0.14536396 -0.51815351  0.6486698  -0.51815351  0.14536396]
---------------------
Eigenvalue =   2.98
Eigenvector  [-2.91898094e-01  6.44046196e-01  4.32644373e-16 -6.44046196e-01
  2.91898094e-01]
---------------------
Eigenvalue =   1.46
Eigenvector  [ 0.44896618 -0.25821367 -0.68081579 -0.25821367  0.44896618]
---------------------
Eigenvalue =   0.00
Eigenvector  [0.4472136 0.4472136 0.4472136 0.4472136 0.4472136]
---------------------
Eigenvalue =   0.37
Eigenvector  [ 6.05187824e-01  3.65715323e-01  4.52240509e-17 -3.65715323e-01
 -6.05187824e-01]
CPU times: user 21.2 ms, sys: 3.73 ms, total: 24.9 ms
Wall time: 20.8 ms


/usr/lib/python3/dist-packages/ipykernel_launcher.py:6: ComplexWarning: Casting complex values to real discards the imaginary part
  
